apiVersion: v1
kind: Secret
metadata:
  name: ztap-secrets
  namespace: ztap-system
type: Opaque
stringData:
  DATABASE_URL: "postgresql://ztap_user:ztap_secure_password_2024@ztap-postgres-service:5432/ztap_db?schema=public"
  SESSION_SECRET: "ztap_ultra_secure_session_key_32chars_long_prod"
  POSTGRES_USER: "ztap_user"
  POSTGRES_PASSWORD: "ztap_secure_password_2024"
  POSTGRES_DB: "ztap_db"
